<?php

/**

 * Created by JetBrains PhpStorm.

 * User: tom

 * Date: 22-3-13

 * Time: 10:48

 * To change this template use File | Settings | File Templates.

 */



define("DELETE_LANGUAGE_SUCCEEDED", "Taaldefinities succesvol verwijderd: ");

define("DELETE_LANGUAGE_FAILED", "Verwijderen van taaldefinitie is mislukt:\n");

define("DELETE_LANGUAGE_WRITABLE", " moet schrijfbaar zijn. verwijderen is mislukt.");

define("DELETE_LANGUAGE_INVALIDCODE", " Geen geldig taalcode gegeven!");

define("DELETE_LANGUAGE_UNABLE_TO_DELETE", " Verwijderen niet gelukt: ");

