<?php

    define("LEARNING_PROMPT_CATEGORIES", "Generate 3 words for each of the following categories: fruits, vegetables, baked goods.");
    define("DEFAULT_PROMPT_CATEGORIES", "Using the exact same xml layout generate one category node appropriate for people in the following age-range: ,range, for each of the following categories: ,subject, each containing ,wpc, items . The answers The words must be different from ; ");
    define("LEARNING_RESULT_CATEGORIES", "<categories><category name='fruit'><item name='banana'/><item name='apple'/><item name='pear'/></category><category name='vegetables'><item name='carrot'/><item name='potato'/><item name='kale'/></category><category name='baked goods'><item name='cake'/><item name='muffin'/><item name='bread'/></category></categories>");