<?PHP     

	/**
	 * 
	 * sharing status folder template language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */

	define("SHARING_INSTRUCTION","To share this folder with a user or a group, please type their name here. A user must have an account on the site to appear in this search. Also select a role to grant the user or group.");

	define("SHARING_NAMES","Names will appear here");

	define("SHARING_CURRENT","This group currently has the following members: ");

    define("SHARING_REMOVE_DESCRIPTION", "Press the button below to remove any sharing rights");

    define("SHARING_REMOVE", "Remove");

    define("SHARING_STOP","Click to leave this group");

	define("SHARING_NOT_SHARED","This folder is not shared");

    define("SHARING_FAIL","You are not a member of this group");

?>