<?PHP     



	/**

	 * 

	 * Gift template english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	// XML SHARING TAB



	define("GIFT_INSTRUCTIONS", "Geef hier een naam in om een kopie van dit leerobject aan iemand anders te geven. De ander moet wel een account op deze XOT server hebben anders verschijnt de naam niet in de lijst.");



	define("GIFT_NAMES", "De namen verschijnen hier");

		

	define("GIFT_FAIL", "U heeft geen rechten op dit template");



