<?PHP     



	/**

	 * 

	 * Gift template english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	// XML SHARING TAB



	define("GIFT_RESPONSE_FAIL", "Excuses, je hebt niet langer rechten op dit template");

	

	define("GIFT_RESPONSE_SUCCESS", "Dit leerobject is succesvol gekopieerd");

			

	define("GIFT_RESPONSE_INSTRUCTIONS","Dit leerobject is gegeven aan ");

			

	define("GIFT_RESPONSE_NAMES","De namen verschijnen hier");



