<?PHP 



	/**

	 * 

	 * media and quota template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	// XML SHARING TAB



	define("MEDIA_AND_QUOTA_USE", "In gebruik");



	define("MEDIA_AND_QUOTA_IMPORT_MEDIA", "Importeer media");



	define("MEDIA_AND_QUOTA_CLICK_FILENAME", "Klik op de bestandsnaam en de link verschijnt hier onder");



	define("MEDIA_AND_QUOTA_BUTTON_IMPORT", "Importeer");



	define("MEDIA_AND_QUOTA_DOWNLOAD", "Download dit bestand");

	

	define("MEDIA_AND_QUOTA_NOT_IN_USE", "Niet in gebruik");

	

	define("MEDIA_AND_QUOTA_DELETE", "Klik om te verwijderen");



    define("MEDIA_AND_QUOTA_UNUSED_DELETE", "Klik hier om alle ongebruikte bestanden te verwijderen");

	

	define("MEDIA_AND_QUOTA_USAGE", "Dit leerobject heeft op dit moment in gebruik");



	define("MEDIA_AND_QUOTA_UPLOAD", "Upload");



	define("MEDIA_AND_QUOTA_LINK", "Klik op de bestandsnaam en de link verschijnt");

	

	define("MEDIA_AND_QUOTA_PUBLISH", "In gebruik / Niet in gebruik geeft aan of het bestand wordt gebruikt in de gepubliceerde versie, niet de ontwikkelversie");

	

	define("MEDIA_AND_QUOTA_FAIL", "Sorry er zijn geen rechten op deze template");



