<?PHP     

	

	/**

	 * 

	 * name select gift language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("NAME_SELECT_GIFT_CLICK","Klik hier");

	

	define("NAME_SELECT_GIFT_INSTRUCTION","Om een kopie van dit template aan de gebruiker te verstrekken");



	define("NAME_SELECT_GIFT_FIND_FAIL","Niemand gevonden met deze gegevens");



