<?PHP



	/**

	 *

	 * properties_library english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



    define("PROPERTIES_LIBRARY_SAVE", "Opslaan");



    define("PROPERTIES_LIBRARY_RENAME", "Hernoem");



	// XML SHARING TAB



	define("PROPERTIES_LIBRARY_XML_TITLE", "XML delen");



	define("PROPERTIES_LIBRARY_XML_DESCRIPTION", "In dit gedeelte vindt het delen van de XML van dit leerobject plaats. Dit werkt alleen wanneer het leerobject gepubliceerd is. Het geeft de mogelijkheid om het leerobject ook in andere systemen te gebruiken.");



	define("PROPERTIES_LIBRARY_XML_SHARING", "XML delen staat");



	define("PROPERTIES_LIBRARY_ON", "aan");



	define("PROPERTIES_LIBRARY_OFF", "uit");



	define("PROPERTIES_LIBRARY_XML_RESTRICT", "De toegang via een bepaalde website kan aangegeven worden");



	define("PROPERTIES_LIBRARY_XML_SAVE", "De aanpasingen zijn opgeslagen");



	define("PROPERTIES_LIBRARY_XML_ERROR", "Sorry, alleen de eigenaar of de co-auteur van dit template kan XML Delen aanzetten");



	//PROJECT INFO PANEL IN THE WORKSPACE - MORE TERSE TEXT

	define ("PROJECT_INFO_NAME", "Naam");



	define ("PROJECT_INFO_ID", "ID");



	define ("PROJECT_INFO_CREATED", "Gemaakt op");



	define ("PROJECT_INFO_MODIFIED", "Laatste keer aangepast op");



	define ("PROJECT_INFO_FRAMEWORK", "Template");



	define ("PROJECT_INFO_RUNTIME", "Runtime");



	define ("PROJECT_INFO_URL", "URL");



	define ("PROJECT_INFO_EMBEDCODE", "Embed Code");



	define ("PROJECT_STATISTICS_UNAVAILABLE", "xAPI tracking data is niet beschikbaar");



	define ("PROJECT_INFO_MEDIA", "Grootte leerobject");



	define ("PROJECT_INFO_ACCESS", "Toegang");



	define ("PROJECT_INFO_SHARED", "Gedeeld");



    define ("PROJECT_INFO_PUBLISHED", "Gepubliceerd");



    define ("PROJECT_INFO_NOTPUBLISHED", "Niet gepubliceerd");



	define ("PROJECT_INFO_NOTSHARED", "Niet gedeeld");



    define("PROJECT_INFO_OAI", "Harvesting (oai) status");



	define ("PROJECT_INFO_PRIVATE", "Privé");



	define ("PROJECT_INFO_PUBLIC", "Publiek");



	define ("PROJECT_INFO_PASSWORD", "Wachtwoord");



	define ("PROJECT_INFO_OTHER", "Anders");



	define ("PROJECT_INFO_ACCESS_SET_AS", "is momenteel ingesteld als");



	define ("PROJECT_INFO_NRVIEWS", ", aantal vertoningen is %n");

	

	define ("PROJECT_INFO_NRVIEWSTITLE", "aantal vertoningen");



	define ("PROJECT_INFO_RSS_SYNDICATION" , "RSS: Project is gepubliceerd via RSS");



	define ("PROJECT_INFO_RSS_SYNDICATION_RSSENABLED" , "RSS is beschikbaar");



	define ("PROJECT_INFO_RSS_SYNDICATION_EXPORTENABLED" , "Export is beschikbaar");



	define ("PROJECT_INFO_RSS_SYNDICATION_SYNDICATIONENABLED" , "Syndication is beschikbaar");



	define("PROJECT_INFO_LTI_PUBLISHED" , "LTI: Het&nbsp;project is gepubliceerd als een LTI 1.1 tool");



	define("PROJECT_INFO_XAPI_PUBLISHED", "xAPI: xAPI is beschikbaar voor dit project via de volgende link:");



    define("GROUP_INFO_NAME", "Name");



    define("GROUP_INFO_MEMBERS", "Leden");



// PROJECT TAB



	define("PROPERTIES_LIBRARY_PROJECT", "Leerobject");



	define("PROPERTIES_LIBRARY_PROJECT_NAME", "Naam leerobject");



	define("PROPERTIES_LIBRARY_PROJECT_CHANGED", "Naam is aangepast");



	define("PROPERTIES_LIBRARY_PROJECT_CREATE", "Dit bestand is gemaakt op");



	define("PROPERTIES_LIBRARY_PROJECT_MODIFY", "Dit bestand is voor het laatst aangepast op");



    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE", "Welke speler is de standaard speler voor dit project?");

	

	define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_WARNING", "Flash wordt niet langer ondersteund en deze checkboxen worden alleen gebruikt om oudere Flash projecten om te zetten naar HTML5.");



    define("PROPERTIES_LIBRARY_PUBLISH_ENGINE", "Default engine");



    define("PROPERTIES_LIBRARY_DEFAULT_HTML5", "Javascript (HTML5)");



    define("PROPERTIES_LIBRARY_DEFAULT_FLASH", "Flash");

	

    define("PROPERTIES_LIBRARY_FLASH_WARNING", "De Flash-speler wordt niet langer ondersteund. Je kunt de standaardspeler wijzigen in HTML5 in de projecteigenschappen");



    define("PROPERTIES_LIBRARY_DEFAULT_ENGINE_CHANGED", "De standaard speler is aangepast");



	define("PROPERTIES_LIBRARY_PROJECT_LINK", "Om anderen toegang te geven tot dit bestand, de link is");



	define("PROPERTIES_LIBRARY_PROJECT_HTML5_LINK", "Om anderen toegang te geven tot de HTML 5 versie, de link is");



	define("PROPERTIES_LIBRARY_PROJECT_IFRAME", "Deze code kan gebruikt worden om het leerobject op de website te embedden");



	define("PROPERTIES_LIBRARY_PROJECT_FAIL", "Sorry, er zijn geen rechten voor dit template");





	// NOTES TAB



	define("PROPERTIES_LIBRARY_NOTES", "Aantekeningen leerobject");



	define("PROPERTIES_LIBRARY_NOTES_EXPLAINED", "Deze aantekeningen zijn alleen zichtbaar voor jou");



	define("PROPERTIES_LIBRARY_NOTES_SAVED", "Aantekeningen opgeslagen");



	define("PROPERTIES_LIBRARY_NOTES_FAIL", "Sorry, alleen de eigenaar of de co-auteur van dit bestand kan hier aantekeningen maken");





	// PEER TAB



	define("PROPERTIES_LIBRARY_PEER", "Peer review");



	define("PROPERTIES_LIBRARY_PEER_EXPLAINED", "<p>In dit gedeelte kan de peer-review voor een&nbsp;project&nbsp;aangemaakt worden. Dit geeft de mogelijkheid om één of meerdere personen een met wachtwoord beveiligde link te sturen, zodat anderen het leerobject kunnen bekijken en de mogelijkheid krijgen via email feedback te geven.&nbsp;</p><p>TIP: controleer eerst of dit werkt door jezelf een test peer-review&nbsp;te sturen voordat je&nbsp;de link naar anderen stuurt.</p>");



	define("PROPERTIES_LIBRARY_PEER_STATUS", "Peer review is");



    define("PROPERTIES_LIBRARY_PEER_LINK", "De link naar de peer review is");



    define("PROPERTIES_LIBRARY_PEER_PASSWORD_PROMPT", "Wachtwoord om reviewers te geven");



    define("PROPERTIES_LIBRARY_PEER_RETOUREMAIL_PROMPT", "E-mail adres (gescheiden met ',') om feedback te zenden naar");



	define("PROPERTIES_LIBRARY_PEER_SAVED", "Peer review instellingen veranderd");



	define("PROPERTIES_LIBRARY_PEER_FAIL", "Sorry, alleen eigenaar of de co-auteur van dit template kunnen een peer review opzetten");





	// SYNDICATION TAB



	define("PROPERTIES_LIBRARY_SYNDICATION", "Open inhoud");



	define("PROPERTIES_LIBRARY_SYNDICATION_EXPLAINED", "Deze tab geeft de mogelijkheid om dit leerobject op de open cursuslijst te plaatsen. Open cursusmateriaal is een set van leermaterialen die instituten openbaar toegankelijk hebben gemaakt om gebruikt te worden door derden. Het adres voor deze website is");



	define("PROPERTIES_LIBRARY_SYNDICATION_PROMPT", "Neem dit leerobject op in de Open cursus feed");



	define("PROPERTIES_LIBRARY_YES", "Ja");



	define("PROPERTIES_LIBRARY_NO", "Nee");



	define("PROPERTIES_LIBRARY_SYNDICATION_CATEGORY", "Kies een categorie voor dit leerobject");



	define("PROPERTIES_LIBRARY_SYNDICATION_LICENCE", "Kies een licentie voor dit leerobject");



	define("PROPERTIES_LIBRARY_SYNDICATION_DESCRIPTION", "Geef een beschrijving voor dit leerobject");



	define("PROPERTIES_LIBRARY_SYNDICATION_KEYWORDS", "Geef een met komma gescheiden lijst van sleutelwoorden voor dit leerobject");



	define("PROPERTIES_LIBRARY_SYNDICATION_SAVED", "De aanpassingen zijn opgeslagen");



	define("PROPERTIES_LIBRARY_SYNDICATION_PUBLIC", "Zet dit leerobject op 'Publiek' in de tab Toegang, voordat syndicatie aangezet wordt,");



	define("PROPERTIES_LIBRARY_SYNDICATION_URL", "Het adres voor deze website syndicatie inhoud is");



	define("PROPERTIES_LIBRARY_SYNDICATION_FAIL", "Sorry, alleen de eigenaar of de co-auteur van dit leerobject kan de syndicatie voor dit leerobject aanmaken");









	// ACCESS TAB



	define("PROPERTIES_LIBRARY_ACCESS", "Dit bestand is op dit moment ingesteld als");



	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC", "Publiek");



	define("PROPERTIES_LIBRARY_ACCESS_PUBLIC_EXPLAINED", "Dit template is beschikbaar voor iedereen op internet");



	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD", "Wachtwoord autorisatie");



	define("PROPERTIES_LIBRARY_ACCESS_PASSWORD_EXPLAINED", "Dit template is beschikbaar voor iedereen met een account binnen dit systeem");



	define("PROPERTIES_LIBRARY_ACCESS_OTHER", "Anders");



	define("PROPERTIES_LIBRARY_ACCESS_OTHER_EXPLAINED", "Gebruik van deze instelling regelt toegang tot het leerobject. De inhoud is alleen beschikbaar voor gebruikers van links naar deze content vanaf een website die je aangeeft. Voeg de URL hier toe.");



	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE", "Privé");



	define("PROPERTIES_LIBRARY_ACCESS_PRIVATE_EXPLAINED", "Dit maakt het template alleen beschikbaar voor auteurs.");



	define("PROPERTIES_LIBRARY_ACCESS_FAIL", "Sorry, alleen auteurs of de co-auteurs hebben toegang tot dit template.");



	define("PROPERTIES_LIBRARY_ACCESS_BUTTON_CHANGE", "Verander toegang");



    define("PROPERTIES_LIBRARY_ACCESS_CHANGED", "De nieuwe toegangsinstellingen zijn opgeslagen.");



	// RSS TAB



	define("PROPERTIES_LIBRARY_RSS", "RSS feeds");



	define("PROPERTIES_LIBRARY_RSS_INCLUDE", "Voeg dit leerobject aan de RSS feeds toe");



	define("PROPERTIES_LIBRARY_RSS_DESCRIPTION", "Er kan ook een beschrijving van het leerobject aan de RSS feed worden toegevoegd.");



	define("PROPERTIES_LIBRARY_RSS_SITE", "Het leerobject kan toegevoegd worden aan de website's RSS feeds. Gebruikers die zich hebben ingeschreven op deze feeds zullen de nieuwe leerobjecten zien. Er zijn verschillende feeds beschikbaar.");



	define("PROPERTIES_LIBRARY_RSS_SITE_LINK", "De hoofdfeed is op");



	define("PROPERTIES_LIBRARY_RSS_PERSONAL", "Dit voegt alle inhoud toe die aangegeven is als inclusief voor de website gebruikers. De eigen RSS feed is beschikbaar op");



	define("PROPERTIES_LIBRARY_RSS_MINE", "Dit voegt alleen de inhoud toe die aangegeven is als inclusief");



	define("PROPERTIES_LIBRARY_RSS_FOLDER", "Wanneer de inhoud in mappen wordt georganiseerd, heeft iedere map zijn eigen RSS feed. Dit maakt het mogelijk toegang te geven tot de leerobjecten in die map. Bekijk de map eigenscappen voor meer details en voor de de link naar de RSS van de map.");



	define("PROPERTIES_LIBRARY_RSS_EXPORT", "Toevoegen van leerobjecten aan de export feed maakt het mogelijk anderen het leerobject te laten downloaden en het leerobject aan te passen.");



	define("PROPERTIES_LIBRARY_RSS_SAVED", "De aanpassingen zijn opgeslagen");



	define("PROPERTIES_LIBRARY_RSS_PUBLIC", "Zet dit leerobject op Publiek in de tab Toegang voordat de RSS feed opties gebruikt worden");



	define("PROPERTIES_LIBRARY_RSS_FAIL", "Sorry, alleen de eigenaar of de co-auteur van dit leerobject kan aantekeningen maken bij dit leerobject");



	// LTI/xAPI TAB



	define("PROPERTIES_LIBRARY_TSUGI_FAIL", "Sorry alleen de&nbsp;eigenaar of co-auteur van het project kan LTI / xAPI-eigenschappen voor het project instellen");



	define("PROPERTIES_LIBRARY_TSUGI", "LTI/xAPI");



	define("PROPERTIES_LIBRARY_TSUGI_DESCRIPTION", "<p>Hier kun je jouw project publiceren als een LTI-tool. Je&nbsp;moet de naam opgeven en je&nbsp;moet de&nbsp;automatisch gegenereerde key, secret&nbsp;en de specifieke URL&nbsp;voor dit project&nbsp;in jouw leeromgeving plaatsen.&nbsp; Je&nbsp;kunt deze automatisch gegenereerde gegevens aanpassen maar onthoud dat deze wel uniek moeten zijn.</p><p>Je kunt er ook voor kiezen de activiteiten te volgen/bekijken via xAPI. Wanneer je&nbsp;dat wil, moet je&nbsp;het eindpunt, de gebruikersnaam en het wachtwoord opgeven van de LRS die de xAPI-statements gaat ontvangen.</p><p>Wanneer&nbsp;je de activiteiten wil&nbsp;volgen zonder LTI, is de enige optie die je hebt&nbsp;een groepnaam toe te voegen. Deze groep moet toegevoegd worden aan de&nbsp;URL (vervang groepnaam door de groepnaam die je wil&nbsp;gebruiken).</p>");



	define("PROPERTIES_LIBRARY_TSUGI_NOTAVAILABLE_DESCRIPTION", "<p>Hier kun je&nbsp;uw project publiceren als een LTI tool indien je&nbsp;TSUGI geïnstalleerd en geconfigureerd hebt&nbsp;als onderdeel van jouw installatie. Om dit&nbsp;moment is&nbsp;Tsugi&nbsp;niet geïnstalleerd. Kijk hier&nbsp;<a href=\"https://xot.xerte.org.uk/play.php?template_id=88\" target=\"_blank\">hoe je&nbsp;Tsugi kunt installeren</a>.</p><p>Je kunt er ook voor kiezen interactiviteiten te volgen via xAPI. Wanneer je&nbsp;dat wil&nbsp;doen moet je&nbsp;een eindpunt, de gebruikersnaam en wachtwoord&nbsp;van de LRS die de xAPI statements gaat ontvangen specificeren.</p><p>Wanneer je&nbsp;de activiteiten wil&nbsp;volgen zonder LTI, is de enige optie die je hebt&nbsp;een groepnaam&nbsp;toe te voegen. Deze groep moet toegevoegd worden aan de&nbsp;URL (vervang groepnaam door de groepnaam die je wil&nbsp;gebruiken).</p>");



	define("PROPERTIES_LIBRARY_TSUGI_PUBLISH", "Publiceer het project via&nbsp;Tsugi als LTI tool");



    define("PROPERTIES_LIBRARY_TSUGI_USEGLOBAL", "Gebruik de standaard ingestelde&nbsp;key(s)&nbsp;en secret(s)&nbsp;(inclusief LTI 1.3)");



    define("PROPERTIES_LIBRARY_TSUGI_USEPRIVATEONLY", "Sta alleen de hieronder geconfigureerde key / secret toe");



	define("PROPERTIES_LIBRARY_TSUGI_NAME", "Naam:");



    define("PROPERTIES_LIBRARY_TSUGI_KEY", "Key:");



	define("PROPERTIES_LIBRARY_TSUGI_SECRET", "Secret:");



	define("PROPERTIES_LIBRARY_TSUGI_ENABLE_XAPI", "Activeer xAPI:");



    define("PROPERTIES_LIBRARY_TSUGI_DASHBOARD_URLS", "Dashboard urls (gescheiden door komma's)");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USEGLOBAL", "Gebruik systeemconfiguratie xAPI LRS:");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_ENDPOINT", "xAPI LRS end-point:");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_USERNAME", "xAPI LRS username:");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_PASSWORD", "xAPI LRS password/secret:");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE", "xAPI LRS student id mode:");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_0", "e-mail");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_1", "hashed e-mail");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_2", "Volledige naam en e-mail");



	define("PROPERTIES_LIBRARY_TSUGI_XAPI_STUDENT_ID_MODE_3", "groep");



	define("PROPERTIES_LIBRARY_TSUGI_UPDATE_BUTTON_LABEL", "Update");



	define("PROPERTIES_LIBRARY_TSUGI_LTI_LAUNCH_URL", "Jouw url is:");



    define("PROPERTIES_LIBRARY_TSUGI_LTI13_LAUNCH_URL", "Jouw LTI 1.3 launch url is:");







