<?PHP     



	/**

	 * 

	 * sharing status template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("SHARING_INSTRUCTION","Om dit leerbject met iemand of met een groep te delen geef je hier de naam aan. De gebruiker moet een account op de site hebben om in deze zoekopdracht te verschijnen.");

	

	define("SHARING_NAMES","De namen verschijnen hier");



	define("SHARING_CURRENT","Dit template wordt tijdelijk gedeeld met : ");



    define("SHARING_CURRENT_FOLDER","Deze map wordt momenteel gedeeld met:");



    define("SHARING_CREATOR", "Eigenaar");



    define("SHARING_COAUTHOR", "Co-auteur");



    define("SHARING_EDITOR","Ontwikkelaar");



	define("SHARING_READONLY","Alleen lezen");



    define("SHARING_SOURCE","van");



    define("SHARING_SOURCE_FOLDER","folder");



    define("SHARING_SOURCE_TEMPLATE","project");



    define("SHARING_REMOVE_DESCRIPTION", "Klik op de knop om alle rechten tot delen te verwijderen");



    define("SHARING_REMOVE", "Verwijder");



	define("SHARING_STOP","Stop delen template");



	define("SHARING_NOT_SHARED","Dit template wordt niet gedeeld");



	define("SHARING_FAIL","Er zijn geen rechten op dit template");



