<?PHP



	/**

	 *

	 * export page template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



    define("XERTE_EXPORT_HTML5", "Exporteer als HTML5");

    define("XERTE_EXPORT_FLASH", "Gebruik Flash");

	define("XERTE_EXPORT_DESCRIPTION","Er zijn verschillende manieren om een leerobject te exporteren. Een geëxporteerde leerobject wordt voor je in een zip bestand verpakt (maar niet verwijderd), om te delen met een andere gebruiker, te gebruiken op het web, of om te importeren in een SCORM LMS of ELO. Je&nbsp;kunt kiezen of je&nbsp;alle bestanden van het leerobject, of alleen de bestanden die door het leerobject gebruikt worden in een zip bestand wil exporteren.");



  define("XERTE_EXPORT_ZIP_ARCHIVE", "Archief exporteren. Volledige export is alleen echt nodig voor het oplossen van xml- of andere problemen.");

  define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Maak Archief zip bestand");



  define("XERTE_EXPORT_ZIP", "Export voor gebruik. Bevat alleen de bestanden die nodig zijn voor importeren in een LMS of ELO zonder SCORM tracking,&nbsp;importeren&nbsp;op een webserver of om te importeren in een andere XOT installatie.");

	define("XERTE_EXPORT_ZIP_LINK","Maak zip bestand ");



	define("XERTE_EXPORT_SCORM", "Export voor SCORM gebruik: op zich zelf staand, SCORM 1.2 or SCORM 2004 dit zorgt ervoor dat de resultaten van bijvoorbeeld Quiz scores in de ELO of LMS terecht komen: ");



	define("XERTE_EXPORT_SCORM_12_LINK","Maak SCORM 1.2 pakket");



	define("XERTE_EXPORT_SCORM_2004_LINK","Maak SCORM 2004 3rd Ed pakket");







