<?PHP     



	/**

	 * 

	 * Xerte peer english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("XERTE_PEER_DESCRIPTION", "Peer review pagina");

	

	define("XERTE_PEER_GUIDANCE", "De maker van dit leerobject verzoekt je dit leerobject te bekijken. Gebruik het onderstaande feedback formulier om jouw reactie te geven.");

	

	define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "Je bent gevraagd om feedback te geven op dit leerobject. Voeg jouw feedback toe en klik op opslaan wanneer je&nbsp;gereed bent. Deze feedback is anoniem.");



    define("XERTE_PEER_BUTTON_SEND", "Verzenden");



    define("XERTE_PEER_PASSWORD", "Wachtwoord");



    define("XERTE_PEER_LOGIN_BUTTON", "Aanmelden");



