<?PHP



	/**

	 * 

	 * file upload english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */	



	define("FILE_UPLOAD_ZIP_FAIL","Bestand uploaden is mislukt");



	define("FILE_UPLOAD_HTML_FAIL","Bestand uploaden is mislukt omdat de HTML pagina PHP code bevatte");



	define("FILE_UPLOAD_SUCCESS","Bestand is succesvol ontvangen");



	define("FILE_UPLOAD_MIME_FAIL","Bestandstype niet toegestaan");

