<?php



/**

 * 

 * import template english language file

 *

 * @author Patrick Lockley

 * @version 1.0

 * @copyright Pat Lockley

 * @package

 */

define("IMPORT_TEMPLATE_ZIP_FAIL", "Dit ZIP bestand is niet juist opgebouwd");



define("IMPORT_TEMPLATE_TEMPLATE_FAIL", "Dit template is niet juist opgebouwd om te kunnen werken met toolkits");



define("IMPORT_TEMPLATE_RLT_FAIL", "Er is geen bestand template.rlt gevonden");



define("IMPORT_TEMPLATE_FOLDER_CREATE", "De map is aangemaakt");



define("IMPORT_TEMPLATE_FOLDER_FAIL", "Error bij aanmaken map");



