<?PHP   

	

	/**

	 * 

	 * Import english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */	



	define("IMPORT_NAME_IF_EMPTY","Geïmporteerd template");

	

	define("IMPORT_SUCCESS","Import succesvol");

	

	define("IMPORT_SUCCESS_REPLACE","Template succesvol vervangen");

	

	define("IMPORT_OWNER_FAIL","Alleen de eigenaar van dit template kan importeren");



	define("IMPORT_FTP_FAIL","Bestandsoverdracht is mislukt");



	define("IMPORT_TYPE_FAIL","Excuses, we kunnen geen template type ophalen voor dit template");



	define("IMPORT_NO_EQUIVALENT_FAIL","Geen valide template gevonden op deze site. Neem&nbsp;contact op met de beheerder.");



	define("IMPORT_ZIP_FAIL","Er kunnen alleen ZIP bestanden worden ge&iuml;mporteerd");

	

	define("IMPORT_XERTE_ONLY","Alleen Xerte templates kunnen op dit moment ge&iuml;mporteerd worden");

	

	define("IMPORT_ZIP_FOLDER_LEVEL","De bestanden in het zip-bestand moeten in de hoofdmap zitten en niet in een van de andere bestanden van het zip-bestand.");



    define("IMPORT_NOT_WRITABLE", "Er zijn geen schrijfrechten voor deze map");



    define("IMPORT_FAILED", "Import is mislukt door een generieke fout. Is het bestand te groot?");



    define("IMPORT_CHECKS_FAILED", "Check op de geïmporteerde bestanden mislukt");



