<?PHP     



	/**

	 * 

	 * delete.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("DELETE_TEMPLATE_NOT_CREATOR", "Sorry, je kunt dit bestand niet verwijderen omdat je niet de auteur bent van dit bestand");

	

	define("DELETE_TEMPLATE_SYNDICATED", "Sorry, je kunt geen leerobject met syndicatie verwijderen. Schakel eerst syndicatie uit om het leerobject te kunnen verwijderen.");

	



