<?PHP    



	/**

	 * 

	 * duplicate_template.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



    define("COPY_OF", "Kopie van");

    define("DUPLICATE_FOLDER_NOT_CREATOR", "Alleen eigenaren en co-auteurs kunnen alle projecten dupliceren in de folder.");

    define("NO_PERMISSION_TO_DUPLICATE_TEMPLATE_OF_FOLDER", "Je hebt geen toestemming om project '{0}' uit map '{1}' te kopiëren.");



