<?PHP     



	/**

	 * 

	 * remove_template.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("REMOVE_TEMPLATE_NOT_CREATOR", "Sorry, alleen de eigenaar van dit bestand kan het verwijderen.");

	

	define("REMOVE_TEMPLATE_SYNDICATED", "Sorry, je kunt geen leerobject met syndicatie verplaatsen. Schakel eerst syndicatie uit om het leerobject te kunnen verplaatsen.");

	



