<?PHP    



	/**

	 * 

	 * my properties (workspace) english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("MY_PROPERTIES_DETAILS", "Mijn gegevens");

	

	define("MY_PROPERTIES_NAME_DETAILS", "Mijn naam in het systeem is");



	define("MY_PROPERTIES_LOGIN_DETAILS", "Mijn laatste login was op");



	define("MY_PROPERTIES_USERNAME_DETAILS", "Mijn gebruikersnaam is");





