<?PHP   



	/**

	 * 

	 * workspace library english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("WORKSPACE_LIBRARY_MY", "Mijn leerobjecten");



	define("WORKSPACE_LIBRARY_SHARED", "Delen projecten");

	

	define("WORKSPACE_LIBRARY_PUBLIC", "Publieke leerobjecten");

	

	define("WORKSPACE_LIBRARY_USAGE", "Gebruikers statistieken");

	

	define("WORKSPACE_LIBRARY_RSS", "Leerobjecten in de RSS");

	

	define("WORKSPACE_LIBRARY_OPEN", "Open Content leerobjecten");

	

	define("WORKSPACE_LIBRARY_PEER", "Peer review");

	

	define("WORKSPACE_LIBRARY_XML", "XML deling");



	define("WORKSPACE_LIBRARY_TEMPLATE_NAME", "Naam");

		

