<?PHP     



	/**

	 * 

	 * management.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("EXTEND_LOGIN","Voeg nieuwe modules toe");



    define("EXTEND_BUTTON_LOGIN","Log in");



    define("EXTEND_NOT_ADMIN_USERNAME","Dit is het panel met nieuwe modules. Alleen de beheerder heeft hier toegang toe.");

	

	define("EXTEND_USERNAME_AND_PASSWORD_EMPTY","Vul gebruikersnaam en wachtwoord in");

	

	define("EXTEND_USERNAME_EMPTY","Vul jouw gebruikersnaam in");

	

	define("EXTEND_PASSWORD_EMPTY","Vul jouw wachtwoord in");

	

	define("EXTEND_LOGON_FAIL","Sorry, jouw gebruikersnam en/of wachtwoord zijn onjuist");

	

	define("EXTEND_TITLE","Voeg nieuwe functies toe");

	

	define("EXTEND_LOGOUT","Log uit");

	

	define("EXTEND_AUTHOR","Auteur");

	

	define("EXTEND_CREATED","Ontwikkeld");

	

	define("EXTEND_SIZE","Grootte");

	

	define("EXTEND_VISIT","Bezoek module pagina");

	

	define("EXTEND_ALREADY","Is al geïnstalleerd");

	

	define("EXTEND_UPGRADE","Upgrade");

	

	define("EXTEND_INSTALL","Installeren");

	

	define("EXTEND_INSTALLED","is geïnstalleerd");

	

	define("EXTEND_ACTIVATE", "Actviveren");

	

	define("EXTEND_LIST", "Lijst modules");

	

	define("EXTEND_MODULE_UPDATE", "Module geüpdate"); 

	

	define("EXTEND_MODULE_INSTALL", "Module geïnstalleerd"); 

	

	define("EXTEND_MODULE_REQUIRES", "Module vereist");

	

	

?>
