<?PHP 



	/**

	 * 

	 * feedback.php english language file

	 *

	 * @author Ron Mitchell

	 * @version 1.0

	 * @copyright Ron Mitchell

	 * @package

	 */

	 



    define("XERTE_FEEDBACK_DESCRIPTION", "Geef feedback");



    define("XERTE_FEEDBACK_GUIDANCE", "<div style=\"margin-left:auto\">Gebruik het onderstaande feedbackformulier om feedback te geven over dit project. Type de feedback in het venster en klik op verzenden.</div>");



define("XERTE_FEEDBACK_LIGHTBOX", "Toon in lightbox");



    define("XERTE_FEEDBACK_CONTACT_INSTRUCTIONS", "Belangrijk: deze feedback is anoniem. Wanneer je will dat er contact opgenomen wordt, voeg dan je&nbsp;naam en je contactgegevens toe aan de&nbsp;reactie voordat je op verzenden klikt.");



    define("XERTE_FEEDBACK_BUTTON_SEND", "Verzend");

?>
