<?PHP 



	/**

	 * 

	 * folder properties english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("FOLDERPROPERTIES_TITLE", "Eigenschappen map");



	define("FOLDERPROPERTIES_DISPLAY_TITLE", "Eigenschappen map");



	define("FOLDERPROPERTIES_TAB_FOLDER", "Eigenschappen map");



	define("FOLDERPROPERTIES_TAB_CONTENT", "Inhoud van deze map");



	define("FOLDERPROPERTIES_TAB_RSS", "RSS feed van deze map");



	define("FOLDERPROPERTIES_TAB_SHARED",  "Gedeelde instellingen");

?>
