<?php



/**

 *

 * index.php english language file

 *

 * @author Patrick Lockley

 * @version 1.0

 * @copyright Pat Lockley

 * @package

 */



define("INDEX_USERNAME_AND_PASSWORD_EMPTY", "Voeg gebruikersnaam en wachtwoord toe");



define("INDEX_USERNAME_EMPTY", "Voeg gebruikersnaam toe");



define("INDEX_PASSWORD_EMPTY", "Voeg wachtwoord toe");



define("INDEX_LDAP_MISSING", "PHP's LDAP bibliotheek moet geïnstalleerd zijn om LDAP authenticatie te gebruiken. In de installatiehandleiding kun je&nbsp;zien welke opties mogelijk zijn.");



define("INDEX_SITE_ADMIN", "Site admins moeten inloggen op de management pagina.");



define("INDEX_LOGON_FAIL", "Sorry, deze combinatie van wachtwoord en gebruikersnaam is onjuist.");



define("INDEX_LOGIN", "Inloggen");



define("INDEX_PSWD_LOGIN", "Log in voor de content");



define("INDEX_PSWD_TITLE", "Xerte login pagina");



define("INDEX_USERNAME", "Gebruikersnaam");



define("INDEX_PASSWORD", "Wachtwoord");



define("INDEX_LOGO_ALT", "Site logo");



define("INDEX_WCAG_LOGO_ALT", "W3C logo");



define("INDEX_OSI_LOGO_ALT", "Open Source Initiative logo");



define("INDEX_APEREO_LOGO_ALT", "Apereo logo");



define("INDEX_XERTE_LOGO_ALT", "Xerte logo");



define("INDEX_HELP_TITLE", "Snel aan de gang");



define("INDEX_HELP_INTRODUCTION", "<p><span style=\"background-color:rgb(246, 246, 246); color:rgb(0, 0, 0); font-family:helvetica neue,helveticaneue,helvetica,arial,sans-serif; font-size:14px\">Zie de&nbsp;</span><a href=\"https://xerte.org.uk/\" target=\"_blank\">Xerte Project website</a><span style=\"background-color:rgb(246, 246, 246); color:rgb(0, 0, 0); font-family:helvetica neue,helveticaneue,helvetica,arial,sans-serif; font-size:14px\">&nbsp;voor&nbsp;</span><a href=\"https://xot.xerte.org.uk/play.php?template_id=150#page2\" target=\"_blank\">handleidingen</a><span style=\"background-color:rgb(246, 246, 246); color:rgb(0, 0, 0); font-family:helvetica neue,helveticaneue,helvetica,arial,sans-serif; font-size:14px\">, voorbeelden en community forums.</span></p>");



define("INDEX_HELP_INTRO_LINK_TEXT","Demo");



define("INDEX_NO_LDAP","PHP's LDAP bibliotheek moet geïnstalleerd zijn om LDAP authenticatie te gebruiken. In de installatiehandleiding kun je zien welke opties mogelijk zijn.");



define("INDEX_FOLDER_PROMPT","Hoe wil je jouw map noemen?");



define("INDEX_FOLDER_NAME","Folder naam");



define("INDEX_WORKSPACE_TITLE","Mijn leerobjecten");



define("INDEX_CREATE","Maak een nieuw leerobject aan");



define("INDEX_DETAILS","Project details");



define("INDEX_SORT","Sorteer de bestanden");



define("INDEX_SEARCH","Zoek");



define("INDEX_SEARCH_PLACEHOLDER", "Naam of Id");



define("INDEX_SORT_A","Alfabetisch A-Z");



define("INDEX_SORT_Z","Alfabetisch Z-A");



define("INDEX_SORT_NEW","Leeftijd (nieuw naar oud)");



define("INDEX_SORT_OLD","Leeftijd (oud naar nieuw)");



define("INDEX_LOG_OUT","Log uit");



define("INDEX_LOGGED_IN_AS","Ingelogd als");



define("INDEX_BUTTON_LOGIN","Log in");



define("INDEX_BUTTON_LOGOUT","Log uit");



define("INDEX_BUTTON_PROPERTIES","Eigenschappen");



define("INDEX_BUTTON_EDIT","Wijzig");



define("INDEX_BUTTON_PREVIEW", "Toon");



define("INDEX_BUTTON_SORT", "Sorteer");



define("INDEX_BUTTON_NEWFOLDER", "Nieuwe map");



define("INDEX_BUTTON_NEWFOLDER_CREATE", "Aanmaken");



define("INDEX_BUTTON_DELETE", "Wis");



define("INDEX_BUTTON_DUPLICATE", "Kopieer");



define("INDEX_BUTTON_PUBLISH", "Publiceer");



define("INDEX_BUTTON_CANCEL", "Annuleer");



define("INDEX_BUTTON_SAVE", "Opslaan");



define("INDEX_XAPI_DASHBOARD_FROM", "Van:");



define("INDEX_XAPI_DASHBOARD_UNTIL", "Tot:");



define("INDEX_XAPI_DASHBOARD_GROUP_SELECT", "Selecteer groep:");



define("INDEX_XAPI_DASHBOARD_GROUP_ALL", "Alle groepen");



define("INDEX_XAPI_DASHBOARD_SHOW_NAMES", "Toon namen en/of e-mail");



define("INDEX_XAPI_DASHBOARD_CLOSE", "Sluit dashboard");



define("INDEX_XAPI_DASHBOARD_DISPLAY_OPTIONS", "Toon opties");



define("INDEX_XAPI_DASHBOARD_SHOW_HIDE_COLUMNS", "Toon / verberg kolommen");



define("INDEX_XAPI_DASHBOARD_QUESTION_OVERVIEW", "Interactie overzicht");



define("INDEX_XAPI_DASHBOARD_PRINT", "Print");



define("INDEX_CHANGE_PASSWORD", "Wachtwoord aanpassen");



define("INDEX_SETTINGS_BUTTON", "Instellingen");
