<?PHP     



	/**

	 * 

	 * management.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("MANAGEMENT_LOGIN","Login voor website administratie");



    define("MANAGEMENT_BUTTON_LOGIN","Log in");

	

	define("MANAGEMENT_USERNAME", "Gebruikersnaam");



	define("MANAGEMENT_PASSWORD", "Wachtwoord");



	define("MANAGEMENT_LOGO_ALT", "Site logo");



	define("MANAGEMENT_WCAG_LOGO_ALT", "W3C logo");



	define("MANAGEMENT_OSI_LOGO_ALT", "Open Source Initiative logo");



	define("MANAGEMENT_APEREO_LOGO_ALT", "Apereo logo");



	define("MANAGEMENT_XERTE_LOGO_ALT", "Xerte logo");



    define("MANAGEMENT_NOT_ADMIN_USERNAME","Dit is het management deel. Alleen administrators hebben toegang tot deze onderdelen.");

	

	define("MANAGEMENT_USERNAME_AND_PASSWORD_EMPTY","Voeg gebruikersnaam en wachtwoord toe");

	

	define("MANAGEMENT_USERNAME_EMPTY","Voeg gebruikersnaam toe");

	

	define("MANAGEMENT_PASSWORD_EMPTY","Voeg wachtwoord toe");

	

	define("MANAGEMENT_LOGON_FAIL","Sorry deze combinatie van gebruikersnaam en wachtwoord is onjuist.");

	

	define("MANAGEMENT_LOGOUT","Log uit");

	

	define("MANAGEMENT_TITLE","Site administratie");

	

	define("MANAGEMENT_MENUBAR_SITE","Site");

	

	define("MANAGEMENT_MENUBAR_CENTRAL","Template");

	

	define("MANAGEMENT_MENUBAR_USERS","Gebruikers");



	define("MANAGEMENT_MENUBAR_USER_GROUPS","Groepen");

	

	define("MANAGEMENT_MENUBAR_TEMPLATES","Gebruikers LO");

	

	define("MANAGEMENT_MENUBAR_LOGS","Logs");

	

	define("MANAGEMENT_MENUBAR_PLAY","Toegang");

	

	define("MANAGEMENT_MENUBAR_CATEGORIES","Categorie");



	define("MANAGEMENT_MENUBAR_EDUCATION", "Educations");



	define("MANAGEMENT_MENUBAR_GROUPINGS","Groeperingen");



	define("MANAGEMENT_MENUBAR_COURSES","Cursussen");



	define("MANAGEMENT_MENUBAR_LICENCES","Licentie");

	

	define("MANAGEMENT_MENUBAR_FEEDS","Feed");

	

	define("MANAGEMENT_MENUBAR_SAVE","Opslaan");



	

?>

