<?PHP 



	/**

	 * 

	 * peer.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("PEER_LOGON_FAIL","Sorry, inloggen is niet gelukt");



    define("XERTE_PEER_DESCRIPTION", "Peer review pagina");



    define("XERTE_PEER_GUIDANCE", "Geef&nbsp; a.u.b. feedback op dit leerobject. Gebruik het formulier hier onder om jouw feedback in te vullen.");



    define("XERTE_PEER_LIGHTBOX", "Bekijk in lightbox");



    define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "<p>Je bent gevraagd om feedback te geven op dit leerobject. Voer jouw feedback in en klik op 'Opslaan' als je&nbsp;klaar bent. Deze feedback is anoniem. Wil je&nbsp;graag dat er contact opgenomen wordt, voeg dan jouw naam en contactgegevens toe aan jouw reactie voordat je&nbsp;op verzenden klikt.</p><p>&nbsp;</p>");



    define("XERTE_PEER_BUTTON_SEND", "Zend");



    define("XERTE_PEER_PASSWORD", "Wachtwoord");



    define("XERTE_PEER_LOGIN_BUTTON", "Log in");

?>
