<?PHP 



	/**

	 * 

	 * properties english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("PROPERTIES_TITLE","Eigenschappen leerobject");

	define("PROPERTIES_DISPLAY_TITLE","Eigenschappen leerobject");

	define("PROPERTIES_TAB_PROJECT","Leerobject");

	define("PROPERTIES_TAB_NOTES","Aantekeningen");

	define("PROPERTIES_TAB_MEDIA","Media en quota");

	define("PROPERTIES_TAB_ACCESS","Toegang");

	define("PROPERTIES_TAB_SHARED","Delen");

	define("PROPERTIES_TAB_RSS","RSS");

	define("PROPERTIES_TAB_OPEN","Open Inhoud");

	define("PROPERTIES_TAB_EXPORT","Export ");

	define("PROPERTIES_TAB_TSUGI","LTI/xAPI");

	define("PROPERTIES_TAB_PEER","Peer review");

	define("PROPERTIES_TAB_GIVE","Geef een kopie");

	define("PROPERTIES_TAB_XML","XML delen");



?>
