<?PHP 



	/**

	 * 

	 * publish properties english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("PUBLISH_PROPERTIES_TITLE","Publiceer het leerobject");

	define("PUBLISH_PROPERTIES_DISPLAY_TITLE","Publiceer het leerobject");

	define("PUBLISH_PROPERTIES_TAB_PROJECT","Leerobject");

	define("PUBLISH_PROPERTIES_TAB_ACCESS","Toegang");

	define("PUBLISH_PROPERTIES_TAB_RSS","RSS");

	define("PUBLISH_PROPERTIES_TAB_OPEN","Open inhoud");

	

?>

