<?PHP 



	/**

	 * 

	 * pwplay.php english language file

	 *

	 * @author Ron MItchell

	 * @version 1.0

	 * @copyright Ron MItchell

	 * @package

	 */

	 

	define("PWPLAY_LOGON_FAIL","Sorry het inloggen is niet gelukt");



    define("XERTE_PWPLAY_DESCRIPTION", "Wachtwoord autorisatie");



    define("XERTE_PWPLAY_GUIDANCE", "Deze projecten&nbsp;worden beschermd door een uniek wachtwoord dat door de auteur is ingesteld.");



define("XERTE_PWPLAY_LIGHTBOX", "Toon in lightbox");



    define("XERTE_PWPLAY_TEXTAREA_INSTRUCTIONS", "Er is om feedback gevraagd op dit project. Voeg je&nbsp;feedback toe&nbsp;en klik op verzenden als je&nbsp;klaar bent. Deze feedback is anoniem. Als je wil dat er contact opgenomen wordt, voeg dan je&nbsp;naam en contactgegevens toe aan jouw&nbsp;reactie voordat je&nbsp;op verzenden klikt.");



    define("XERTE_PWPLAY_BUTTON_SEND", "Verzend");



    define("XERTE_PWPLAY_PASSWORD", "Wachtwoord");



    define("XERTE_PWPLAY_LOGIN_BUTTON", "Inloggen");

?>
