<?PHP 



	/**

	 * 

	 * rss english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("RSS_DESCRIPTION","Een feed welke alle publieke leerobjecten bevat van");

	define("RSS_LANGUAGE","en-gb ");

	define("RSS_DB_FAIL","Sorry, het systeem kan geen contact met de database maken op het moment. De mysql error is ");

	define("RSS_LO","'s leerobjecten");

	define("RSS_PLURAL", "'s");

	define("RSS_FEED_DESC","Een feed welke alles bevat van"); 

	define("RSS_FEED_PUBLIC","'s  publieke leerobjecten van de");

	define("RSS_USER_LO","'s leerobjecten");

	define("RSS_FEED_USER","Een feed welke alles bevat van");

	define("RSS_USER_LO_LOWER","'s leerobjecten - ");

	define("RSS_FROM","van de");

	define("RSS_SITE","'s site");

	define("RSS_DEVELOP","is ontwikkeld door");

 

 ?>
