<?PHP 



	/**

	 * 

	 * Syndicate english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("SYNDICATE_DESCRIPTION","Deze RSS feed bevat een lijst van alle gesyndiceerde content van de Xerte Online Toolkits installatie op ");

	define("SYNDICATE_LANGUAGE","en-gb");

	define("SYNDICATE_DOWNLOAD","Download de content van");

	define("SYNDICATE_DOWNLOAD_SCORM","Download dit als een  SCORM-pakket van");

	define("SYNDICATE_LICENCE","Deze content heeft de volgende licentie");



?>
