<?PHP 



	/**

	 * 

	 * properties english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

	define("USER_SETTINGS_PASSWORD_TITLE","Wachtwoord aanpassen");

	define("USER_SETTINGS_PASSWORD_DISPLAY_TITLE","Wachtwoord aanpassen");



	define("USER_SETTINGS_PASSWORD_OLD", "Wachtwoord aanpassen");

	define("USER_SETTINGS_PASSWORD_NEW", "Nieuw wachtwoord");

	define("USER_SETTINGS_PASSWORD_NEW_REPEAT", "Herhaal nieuwe wachtwoord");

    define("USER_SETTINGS_PASSWORD_SUBMIT", "Verzend");



?>
