<?PHP 



	/**

	 * 

	 * workspace properties english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 

    define("PHP_ERROR","Status berichten");

    define("WORKSPACE_PROPERTIES_TITLE","Eigenschappen werkruimte gebruiker");

	define("WORKSPACE_PROPERTIES_DISPLAY_TITLE","Eigenschappen werkruimte");

	define("WORKSPACE_PROPERTIES_TAB_DETAILS","Mijn gegevens");

	define("WORKSPACE_PROPERTIES_TAB_PROJECTS","Mijn leerobjecten");

	define("WORKSPACE_PROPERTIES_TAB_FEEDS","Mijn feeds");

	define("WORKSPACE_PROPERTIES_TAB_IMPORT","Import");

	define("WORKSPACE_PROPERTIES_TAB_API","API");

	

?>
