<?PHP 

	/**
	 * 
	 * folder properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("GROUPPROPERTIES_TITLE", "Group properties");

	define("GROUPPROPERTIES_DISPLAY_TITLE", "Group Properties");

	define("GROUPPROPERTIES_TAB_GROUP", "Group Properties");

	define("GROUPPROPERTIES_TAB_CONTENT", "Group Contents");

	//define("FOLDERPROPERTIES_TAB_RSS", "Folder RSS feed");

	define("GROUPPROPERTIES_TAB_SHARED", "Members");
?>