<?PHP 

	/**
	 * 
	 * properties english language file
	 *
	 * @author Patrick Lockley
	 * @version 1.0
	 * @copyright Pat Lockley
	 * @package
	 */
	 
	define("USER_SETTINGS_PASSWORD_TITLE","Change Password");
	define("USER_SETTINGS_PASSWORD_DISPLAY_TITLE","Change Password");

	define("USER_SETTINGS_PASSWORD_OLD", "Current Password");
	define("USER_SETTINGS_PASSWORD_NEW", "New Password");
	define("USER_SETTINGS_PASSWORD_NEW_REPEAT", "Repeat new Password");
    define("USER_SETTINGS_PASSWORD_SUBMIT", "Submit");

    define("USER_SETTINGS_EDITOR_OPEN_MODE", "Open editor in");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_POPUP", "Popup window");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_BLANK", "New tab");
    define("USER_SETTINGS_EDITOR_OPEN_MODE_LIGHTBOX", "Lightbox (in page)");

?>