<?PHP



	/**

	 *

	 * export page template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



    define("XERTE_EXPORT_HTML5", "Export met Javascript (ook wel bekend als HTML5) runtime");

    define("XERTE_EXPORT_FLASH", "Export met Flash runtime");

	define("XERTE_EXPORT_DESCRIPTION","Er zijn diverse manieren om een leerobject te exporteren. Een geëxporteerd leerobject wordt verpakt in een zip-pakket die je kunt delen met andere gebruikers, voor gebruik op het web, of om in een SCORM compatible LMS of ELO. Je kunt er voor kiezen om alle bestanden van het leerobject te exporteren of alleen de gebruikte bestanden.");



  define("XERTE_EXPORT_ZIP_ARCHIVE", "Archief exporteren. Volledige export is alleen echt nodig voor het oplossen van xml- of andere problemen.");

  define("XERTE_EXPORT_ZIP_ARCHIVE_LINK","Maak Archief zip.");



  define("XERTE_EXPORT_ZIP", "Export voor productie. Bevat alleen de bestanden die nodig zijn voor de import in een LMS of ELO zonder SCORM tracking, importeren in een webserver&nbsp;of de import in een andere Xerte Online Toolkits installatie.");

	define("XERTE_EXPORT_ZIP_LINK","Maak productie zip.");



	define("XERTE_EXPORT_SCORM", "Export voor SCORM 1.2 of SCORM 2004 pakketten die tracking van de resultaten van enkele interactieve pagina&#39;s (o.a. quiz, categorie, meerkeuzevraag) mogelijk maakt.");



	define("XERTE_EXPORT_SCORM_12_LINK","Maak een SCORM 1.2 pakket");



	define("XERTE_EXPORT_SCORM_2004_LINK","Maak een SCORM 2004 3rd Ed pakket");







