<?PHP     



	/**

	 * 

	 * Xerte peer english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("XERTE_PEER_DESCRIPTION", "Peer review pagina");

	

	define("XERTE_PEER_GUIDANCE", "Graag jouw feedback op dit leerobject. Gebruik het formulier hier onder om jouw feedback te verzenden.");

	

	define("XERTE_PEER_TEXTAREA_INSTRUCTIONS", "Je bent gevraagd om feedback op dit leerobject te geven. Vul&nbsp;alstublieft jouw feedback in en klik op 'Opslaan' wanneer je klaar bent. Deze feedback is anoniem.");



    define("XERTE_PEER_BUTTON_SEND", "Opslaan");



    define("XERTE_PEER_PASSWORD", "Wachtwoord");



    define("XERTE_PEER_LOGIN_BUTTON", "Inloggen");



