<?PHP



	/**

	 *

	 * peer review language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */





	define("PEER_REVIEW_FEEDBACK","Feedback op het leerobject");



	define("PEER_REVIEW_EMAIL_GREETING","Hallo,");



	define("PEER_REVIEW_EMAIL_INTRO","Er is feedback gegeven op het leerobject.");



	define("PEER_REVIEW_EMAIL_YOURS","Bedankt voor het gebruiken van Xerte");



	define("PEER_REVIEW_EMAIL_SIGNATURE","Het Xerte Project Team");



    define("PEER_REVIEW_IDENTIFICATION","Deze e-mail is verzonden als feedback op leerobject {template_id} gemaakt door {creator} van de Xerte-installatie die wordt gehost op {url}");



    define("PEER_REVIEW_USER_FEEDBACK","De feedback is naar de gebruiker verzonden");



	define("PEER_REVIEW_PROBLEM","Er heeft zich een probleem voorgedaan");

