<?PHP



	/**

	 * 

	 * management library english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("MANAGEMENT_LIBRARY_REMOVE", "Verwijder");

    define("MANAGEMENT_LIBRARY_EXPAND", "Toon/Verberg");

    define("MANAGEMENT_LIBRARY_COLLAPSE", "Verberg");

    define("MANAGEMENT_LIBRARY_ADD", "Voeg toe");

	define("MANAGEMENT_LIBRARY_VIEW", "Toon");



	define("MANAGEMENT_LIBRARY_ADD_CATEGORY", "Voeg een nieuwe categorie toe");

	define("MANAGEMENT_LIBRARY_NEW_CATEGORY", "De nieuwe categorie");

	define("MANAGEMENT_LIBRARY_NEW_CATEGORY_NAME", "Voeg naam toe");

	define("MANAGEMENT_LIBRARY_NEW_LABEL", "Toevoegen");

	define("MANAGEMENT_LIBRARY_EXISTING_CATEGORIES", "Beheer bestaande categoriën");



    define("MANAGEMENT_LIBRARY_ADD_EDUCATION", "Voeg een nieuw educatie niveau toe");

    define("MANAGEMENT_LIBRARY_NEW_EDUCATION", "Het nieuwe educatie niveau is");

    define("MANAGEMENT_LIBRARY_NEW_EDUCATION_NAME", "Voeg naam toe");

    define("MANAGEMENT_LIBRARY_EXISTING_EDUCATION", "Manage bestaande educatie niveaus");



    define("MANAGEMENT_LIBRARY_ADD_GROUPING", "Voeg een nieuwe groepering toe");

    define("MANAGEMENT_LIBRARY_NEW_GROUPING", "De nieuwe groepering is");

    define("MANAGEMENT_LIBRARY_NEW_GROUPING_NAME", "Voeg naam toe");

    define("MANAGEMENT_LIBRARY_EXISTING_GROUPINGS", "Beheer de bestaande groeperingen");



    define("MANAGEMENT_LIBRARY_ADD_COURSE", "Voeg een nieuwe cursus toe");

    define("MANAGEMENT_LIBRARY_NEW_COURSE", "De nieuwe cursus is");

    define("MANAGEMENT_LIBRARY_NEW_COURSE_NAME", "Voeg de naam toe");

    define("MANAGEMENT_LIBRARY_EXISTING_COURSES", "Manage bestaande cursussen");

    define("MANAGEMENT_COURSE_FREE_TEXT_ENABLE", "<p>Schakel vrije tekstinvoer voor cursussen in</p><p>&nbsp;</p>");



    define("MANAGEMENT_LIBRARY_FEEDS_NO_FEEDS", "Er zijn nog geen projecten toegevoegd aan deze RSS feeds.");

	define("MANAGEMENT_LIBRARY_REMOVE_RSS", "Verwijder uit RSS");

	define("MANAGEMENT_LIBRARY_REMOVE_EXPORT", "Verwijder uit export");

	define("MANAGEMENT_LIBRARY_REMOVE_SYNDICATION", "Verwijder uit syndicatie");



	define("MANAGEMENT_LIBRARY_ADD_SECURITY", "Voeg nieuwe toegangs-instelling toe");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY", "De naam van de toegangs-instelling is");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY_NAME", "Voeg naam toe");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DATA", "De toegangs-instelling is (url)");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DETAILS", "Voeg het webadres of IP toe");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY_INFO", "De toegangsinfo is");

	define("MANAGEMENT_LIBRARY_NEW_SECURITY_DESCRIPTION", "Voeg de beschrijving die de gebruikers zien hier toe");



	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY", "Beheer de bestaande instellingen");

		

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_IS", "De toegangs-instelling is");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_DATA", "De toegangs-instelling is (url)");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_INFO", "De toegangsinfo is");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_REMOVE", "Verwijder de instelling");

	define("MANAGEMENT_LIBRARY_EXISTING_SECURITY_WARNING", "Bij het verwijderen van deze instelling wordt alle inhoud voor deze optie op privé ingesteld. Je moet de gebruikers hier eerst van op de hoogte stellen.");

	

	define("MANAGEMENT_LIBRARY_NEW_LICENCE", "Voeg een nieuwe licentie toe");

	define("MANAGEMENT_LIBRARY_NEW_LICENCE_DETAILS", "De nieuwe licentie is");

	define("MANAGEMENT_LIBRARY_NEW_LICENCE_NAME", "Voeg Licentie naam toe");

	define("MANAGEMENT_LIBRARY_MANAGE_LICENCES", "Beheer de bestaande licentie");



	define("MANAGEMENT_LIBRARY_FAIL", "Deze optie is alleen voor administrators ");



    define("MANAGEMENT_LIBRARY_ADD_LANGUAGE", " Geen geldig taal definitie bestand!");

    define("MANAGEMENT_LIBRARY_EXISTING_LANGUAGES", "Beheer de bestaande taaldefinities");

    define("MANAGEMENT_LIBRARY_LANGUAGE_INSTALL", "Installeer taal");

    define("MANAGEMENT_LIBRARY_LANGUAGES", "Taal instellingen");

    define("MANAGEMENT_LIBRARY_LANGUAGES_EXPLAINED", "Installeer en vervang the taal door een taal-definitie bestand te kiezen. Nieuwe taal definities zijn te vinden op de Xerte Community website (http://www.xerte.org.uk). Er zijn drie verschillende soorten taal-definitie bestanden. Elk van de drie is te gebruiken.");

    define("MANAGEMENT_LIBRARY_LANGUAGES_UPDATED", "Taal definities zijn bijgewerkt");

