<?PHP



	/**

	 *

	 * management site english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 *

	 * PLEASE USE DOUBLE QUOTES IN THESE FILES, OTHERWISE XERTE TRANS DOES NOT WORK!

	 *

	 */





	define("MANAGEMENT_SITE_TITLE", "Site instellingen (HTML /afbeeldingen)");



    define("MANAGEMENT_SITE_REGISTER_TEXT", "<h2>Registreer</h2><p>Neem&nbsp;a.u.b. even de tijd om jouw installatie te registreren.</p><p>De registreerknop hieronder opent een registratieformulier op de Xerte Community Web Site. Hiermee kun je jouw installatie aanmelden bij de community.</p><p>Je kunt er dan ook voor kiezen een melding te ontvangen over updates en/of belangrijke bug fixes.</p>");



    define("MANAGEMENT_SITE_REGISTER", "Registreer");



    define("MANAGEMENT_SITE_URL", "De site URL is (dit is de URL van deze site - door dit te veranderen verandert de URL niet)");



	define("MANAGEMENT_SITE_TITLE_HTML", "De site titel is (dit is de HTML titel tag inhoud) ");



	define("MANAGEMENT_SITE_NAME", "De site naam is (dit is een deel van de index.php en de RSS en syndicatie feeds)");



	define("MANAGEMENT_SITE_LOGO", "De logo van de site is (het logo staat linksboven)");



	define("MANAGEMENT_SITE_LOGO_ORG", "Het logo van de organisatie is (het logo rechtsboven)");



	define("MANAGEMENT_SITE_WELCOME", "Het welkom bericht is (de tekst boven de hulpmiddelen in index.php)");



	define("MANAGEMENT_SITE_TEXT", "De site tekst is (de tekst onder het xerte logo in index.php)");



    define("MANAGEMENT_TUTORIAL_TEXT", "Introtekst");



	define("MANAGEMENT_SITE_NEWS", "Tekstvak 3 (onder na login)");



	define("MANAGEMENT_SITE_POD_ONE", "Tekstvak 1 (onder na login)");



	define("MANAGEMENT_SITE_POD_TWO", "Tekstvak 2 (onder na login)");



	define("MANAGEMENT_SITE_COPYRIGHT", "Copyright bericht");



	define("MANAGEMENT_SITE_DEMONSTRATION", "De URL van de demonstratie pagina is");



	define("MANAGEMENT_SITE_LOGIN_FORM", "De form string is (De code die HTML format voor de login box behandelt)");



	define("MANAGEMENT_SITE_PEER_FORM", "De peer form string is (De code die HTML format voor de peer review login box behandelt)");



	define("MANAGEMENT_SITE_FEEDBACK", "De site's feedback lijst is (een semi-kolom gescheiden lijst met email adressen die feedback van de feedback pagina ontvangen)");



	define("MANAGEMENT_SITE_SERVER", "Server instellingen");



	define("MANAGEMENT_VIEW", "Toon");



	define("MANAGEMENT_SITE_HTACCESS", "De HTACCESS instelling is (of er nu wel of geen .htaccess bestand op de site gebruikt wordt)");



	define("MANAGEMENT_SITE_SESSION_NAME", "De PHP sessie naam is ");



	define("MANAGEMENT_SITE_ENABLE_MIME", "Whether the MIME file type check should be applied to file uploads ");



	define("MANAGEMENT_SITE_MIME", "Het toegestane upload type voor media en quota pagina zijn");



	define("MANAGEMENT_SITE_ENABLE_FILE_EXT", "Of de check van de bestandsextensie moet worden ingeschakeld voor ge&iuml;mporteerde bestanden");



	define("MANAGEMENT_SITE_FILE_EXTENSIONS", "De&nbsp;blacklisted bestandsextensies voor de ge&iuml;mproteerde bestanden zijn");



	define("MANAGEMENT_SITE_ENABLE_CLAMAV_CHK", "Of de antiviruscontrole moet worden ingeschakeld voor ge&iuml;mporteerde bestanden");



	define("MANAGEMENT_SITE_CLAMAV_CMD", "De volledige padnaam naar&nbsp;het antivirus commando (voor prestaties waarvoor een&nbsp;daemon-proces wordt aanbevolen)");



	define("MANAGEMENT_SITE_CLAMAV_OPTS", "<p>Een door spaties gescheiden lijst met opties die moeten worden gebruikt met&nbsp;het bovenstaande commando</p><p>&nbsp;</p>");



	define("MANAGEMENT_SITE_INTEGRATION", "Het integratie config pad is  ");



	define("MANAGEMENT_SITE_ADMIN_USER", "De admin gebruikersnaam is ");



	define("MANAGEMENT_SITE_ADMIN_PASSWORD", "Het admin wachtwoord is ");



	define("MANAGEMENT_SITE_RSS", "RSS instellingen");



	define("MANAGEMENT_SITE_RSS_TITLE", "De RSS feed titel is ");



	define("MANAGEMENT_SITE_RSS_PUBLISHER", "Naam organisatie");



	define("MANAGEMENT_SITE_RSS_RIGHTS", "De standaard syndicatie rechten voor de syndicatie inhoud zijn");



	define("MANAGEMENT_SITE_RSS_LICENCE", "De standaard syndicatie licentie voor de syndicatie inhoud is");



	define("MANAGEMENT_SITE_PATH", "Pad instellingen");



	define("MANAGEMENT_SITE_PATH_MODULE", "Het module pad is");



	define("MANAGEMENT_SITE_PATH_WEBSITE", "Het website code pad is");



	define("MANAGEMENT_SITE_PATH_SHORT", "Het snelkoppeling bestandsruimte pad is");



	define("MANAGEMENT_SITE_PATH_LIBRARY", "Het bibliotheek pad is");



	define("MANAGEMENT_SITE_PATH_ROOT", "Het root bestand pad is");



	define("MANAGEMENT_SITE_PATH_IMPORT", "Het import pad is");



	define("MANAGEMENT_SITE_SQL", "SQL query instellingen");



	define("MANAGEMENT_SITE_QUERY", "De afspeel edit voorvertoning query is ");



	define("MANAGEMENT_SITE_ERROR_HANDLING", "Error behandeling instellingen");



	define("MANAGEMENT_SITE_ERROR_EMAIL", "De email lijst is (accounts die een email ontvangen bij een error in de log bestanden)");



	define("MANAGEMENT_SITE_ERROR_EMAIL_ACCOUNT", "Het error log bericht is (zet op waar voor log errors)");



	define("MANAGEMENT_SITE_ERROR_MAX", "De maximum&nbsp;error grootte is (het maximum&nbsp;aantal in de error log)");



	define("MANAGEMENT_SITE_LDAP", "LDAP instellingen");



	define("MANAGEMENT_SITE_LDAP_DELIMIT", "Er kan een set up van multiple hosts toegevoegd worden door de invoer van elk veld met een $$$ string als scheidingsteken toe te voegen.");



	define("MANAGEMENT_SITE_LDAP_HOST", "De LDAP host is ");



	define("MANAGEMENT_SITE_LDAP_PORT", "De LDAP poort is ");



	define("MANAGEMENT_SITE_LDAP_PASSWORD", "Het LDAP wachtwoord is");



	define("MANAGEMENT_SITE_LDAP_BASE", "De LDAP base is ");



	define("MANAGEMENT_SITE_LDAP_BIND", "De LDAP bind is ");



	define("MANAGEMENT_SITE_LDAP_FILTER_ONE", "De LDAP main filter is ");



	define("MANAGEMENT_SITE_LDAP_FILTER_TWO", "De LDAP second filter is");



	define("MANAGEMENT_SITE_XERTE", "Xerte Instellingen");



	define("MANAGEMENT_SITE_XERTE_SAVE", "Het  Flash opslaan pad is ");



	define("MANAGEMENT_SITE_XERTE_UPLOAD", "Het Flash upload pad is");



	define("MANAGEMENT_SITE_XERTE_PREVIEW", "Het Flash voorvertoning pad is");



	define("MANAGEMENT_SITE_XERTE_SKIN", "De flash FLV skin is");



	define("MANAGEMENT_SITE_EMAIL", "E-mail ");



	define("MANAGEMENT_SITE_EMAIL_ACCOUNT", "Het website email account is");



	define("MANAGEMENT_SITE_EMAIL_HEADERS", "De site email titels zijn (hebruik het * symbool om een nieuwe regel te presenteren)");



	define("MANAGEMENT_SITE_EMAIL_SUFFIX", "De site email om toe te voegen aan de gebruikersnaam is");



	define("MANAGEMENT_SITE_PROXY", "De site's proxy host is");



	define("MANAGEMENT_SITE_PROXY_PORT", "De site's proxy poort is ");



	define("MANAGEMENT_SITE_PROXY_EXPLAINED", "Bij het direct aanpassen van RSS proxy.php bestand (in de root map), is het mogelijk 4 proxys en poorten aan te maken (indien nodig).");



  define("MANAGEMENT_SITE_AUTH_DETAILS", "Authenticatie instellingen");



  define("MANAGEMENT_SITE_AUTH_METHOD", "Te gebruiken authenticatie methode");



  define("MANAGEMENT_SITE_LTI","LTI/Moodle instellingen (niet TSUGI-LTI)");



  define("MANAGEMENT_SITE_XAPI", "xAPI instellingen");



  define("MANAGEMENT_SITE_XAPI_ENDPOINT", "xAPI endpoint (url)");



  define("MANAGEMENT_SITE_XAPI_KEY", "xAPI key (username)");



  define("MANAGEMENT_SITE_XAPI_SECRET", "xAPI secret (password)");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_ENABLE", "Aanzetten xAPI dashboard");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_NONANONYMOUS_VIEW", "Aanzetten niet anonieme overzicht (indien beschikbaar)");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_FORCE_ANONYMOUS_LRS", "Bepaal&nbsp;dat alleen anonieme actoren (groeps- en gehashte e-mails) worden opgeslagen in LRS");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_DEFAULT_PERIOD", "xAPI dashboard standaard periode (in dagen)");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_MINIMUM_ROLE", "xAPI dashboard minimale rol om het dashboard te mogen bekijken");



  define("MANAGEMENT_SITE_XAPI_DASHBOARD_ALLOWED_URLS", "Welke xAPI urls tonen in dashboard (gescheiden door komma&#39;s)");



define("MANAGEMENT_SITE_SOCIALICONS","Social Icons instellingen (voorkomt gebruik van cookies)");



define("MANAGEMENT_SITE_SOCIALICONS_GLOBALDISABLE","Zet de social icons standaard uit&nbsp;(voorkomt gebruik van&nbsp;cookies)");



define("MANAGEMENT_SITE_SOCIALICONS_ALLOWOVERRIDE","Geef auteurs toestemming soxiale media iconen te gebruiken.");





define("LTI_TOGGLE","Toon");



define("LTI_KEYS_NAME","LTI Key Omschrijving");

define("LTI_KEYS_KEY","De LTI Key ");

define("LTI_KEYS_SECRET","De LTI Keys Secret ");

define("LTI_KEYS_CONTEXT_ID","Een overide voor de LTI Context ");

define("LTI_KEYS_DELETED","Wanneer verwijderd");

define("LTI_KEYS_UPDATED_ON","Wanneer voor het laatst geüpdate");



define("MANAGEMENT_SITE_LTI_KEYS","LTI Keys ");



define("LTI_KEYS_NEW","Nieuw");

define("LTI_KEYS_DELETE","Verwijderd");

define("LTI_KEYS_ADD","Voeg nieuwe LTI Key toe");

define("LTI_KEYS_ADD_SUBMIT","Voeg nieuwe LTI Key toe");

define("LTI_KEYS_EDIT_SUBMIT","Bewaar LTI Key");

define("LTI_KEYS_DELETE_SUBMIT","Verwijder LTI Key");



