<?PHP     



	/**

	 * 

	 * management templates sync english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("SYNC_INSTALL", "template geïnstalleerd");



	define("SYNC_UPDATE", "Template ge&uuml;pdate");

	

	define("SYNC_REQUIRES", "vereiste module kan niet geïnstalleerd worden");

	

	define("SYNC_RETURN", "Klik op centrale templates om terug te keren naar de template management paginaClick on central templates to return to the template management page");

