<?PHP



	/**

	 * 

	 * management template english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("TEMPLATE_UPLOAD", "Upload een template");



	define("TEMPLATE_UPLOAD_BUTTON", "Upload");



	define("TEMPLATE_VIEW", "Toon");



    define("TEMPLATE_UPDATE_EXPLANATION", "<h2>Hoofdtemplate</h2><p>Om een template toe te voegen aan de installatie, upload het template via ftp en klik op de knop hieronder voor de update. <strong>LET OP!</strong> Dit geldt alleen voor nieuwe hoofdtemplates en <u><strong>NIET</strong></u> <strong>voor subtemplates of thema's</strong>. Bij het gebruik van deze functie wordt de vertaling van de hoofdtemplates (XOT, Bootstrap en Decision) terug gezet naar de standdaard (Engels). Deze zal dan opnieuw vertaald moeten worden bij de drie hoofdtemplates.&nbsp;</p>");



	define("TEMPLATE_UPDATE", "Update template lijst");

	

	define("TEMPLATE_MANAGE", "<h3>Beheer bestaande templates</h3>");



	define("TEMPLATE_TYPE", "Dit template type is");



	define("TEMPLATE_SUB_TYPE", "Dit template is een sub-template van");



	define("TEMPLATE_SUB_DELETE", "Verwijder");

	

	define("TEMPLATE_INSTALL", "Dit template is verbonden aan de module");

	

	define("TEMPLATE_INSTALL_INST", "Alstublieft installeren");



	define("TEMPLATE_VERSION", "Dit is template versie nummer"); 



	define("TEMPLATE_DESCRIPTION", "De beschrijving van dit template is"); 



	define("TEMPLATE_UPLOAD_DATE", "Dit template was geupload op");



	define("TEMPLATE_NAME", "Dit template heeft de volgende naam voor de gebruikers");



	define("TEMPLATE_EXAMPLE", "Dit template heeft de volgende voorbeelden (0 betekent geen voorbeeld)");



	define("TEMPLATE_ACCESS", "De volgende gebruikers hebben toegang tot dit template (*betekent iedereen)");



	define("TEMPLATE_DATE_UPLOAD", "De data geupload voor dit template is (de laatst aangepaste eerst/de meest recente eerst)");



	define("TEMPLATE_STATUS", "Dit template is op dit moment ingesteld als");



	define("TEMPLATE_ACTIVE", "Actief");



	define("TEMPLATE_INACTIVE", "Niet actief");



	define("TEMPLATE_REPLACE", "Upload een nieuwe versie van dit template");



	define("TEMPLATE_SUB_PAGES_TITLEONLY", "Toon alleen de titel van het leerobject in de hoofdpagina van de 'Eenvoudige' modus van de wizard.");



	define("TEMPLATE_SUB_PAGES_SELECT_TITLEONLY", "Toon alleen de titel");



	define("TEMPLATE_SUB_PAGES", "Selecteer de pagina's die gebruikt mogen worden in de 'Eenvoudige' modus van de wizard. Wanneer alle pagina's gebruikt mogen worden (standaard), dan is de 'Eenvoudige' modus van de editor uitgezet.");



	define("TEMPLATE_SUB_PAGES_SELECT_ALL", "Toggle alle pagina's aan of uit");



	define("TEMPLATE_ADD_EXPLANATION", "<h2>Sub-templates</h2><p>Importeer een geëxporteerd leerobject als een nieuw&nbsp;sub-template. Als het&nbsp;sub-template&nbsp;al bestaat, wordt deze vervangen. Het veld 'Template naam' identificeert het&nbsp;sub-template. Het veld&nbsp; 'Getoonde template naam' is de naam die aan de gebruiker wordt getoond.</p><p>Gebruik geen spaties of andere speciale tekens in de template naam, omdat deze naam wordt gebruikt als mapnaam. Als je speciale tekens of spaties gebruikt, worden deze vervangen door het teken '_'.</p>");



    define("TEMPLATE_ADD", "Voeg template toe");



    define("TEMPLATE_UPLOAD_FILE", "Voeg bestand toe");



    define("TEMPLATE_UPLOAD_TEMPLATENAME", "Template naam");



    define("TEMPLATE_UPLOAD_TEMPLATEDISPLAYNAME", "Getoonde template naam");



    define("TEMPLATE_UPLOAD_TEMPLATEDESCRIPTION", "Template beschrijving");

