<?php

/**

 * Created by PhpStorm.

 * User: Akshay

 * Date: 10/24/2018

 * Time: 4:01 PM

 */



    define("TEMPLATE_UPLOAD_INCORRECT_FILE_TYPE", "Het bestand dat je&nbsp;probeert te uploaden is geen&nbsp;.zip bestand. Probeer&nbsp;het a.u.b. nog een keer!");



    define("TEMPLATE_UPLOAD_CORRECT", "Het bestand is succesvol uitgepakt!");



    define("TEMPLATE_UPLOAD_ERROR", "Het is niet gelukt het bestand te uploaden.&nbsp;Probeert het a.u.b. nog een keer!");



    define("TEMPLATE_UPLOAD_HAS_NO_TEMPLATE_XML", "Het&nbsp;.zip bestand bevat geen template.xml!");



    define("TEMPLATE_UPLOAD_HAS_NO_MEDIA", "Het .zip bestand bevat geen media folder!");



    define("TEMPLATE_UPLOAD_EMPTY_DESCRIPTION", "Beschrijving kan niet leeg zijn!");



    define("TEMPLATE_UPLOAD_CANT_DETERMINE_PARENT_TEMPLATE", "Kan het hoofdtemplate niet vaststellen. De&nbsp;template.xml in het zip bestand is niet geldig.");



    define("TEMPLATE_UPLOAD_INVALID_PARENT_TEMPLATE", "Hoofdtemplate &#39;{0}&#39; wordt niet herkend als een geldig hoofdtemplate in deze installatie.");



    define("TEMPLATE_UPLOAD_FILE_CANT_BE_UPLOADED", "Er ging iets fout bij het verplaatsen van het&nbsp;huidige zip bestand! Probeer het a.u.b. nog een keer!");



    define("TEMPLATE_UPLOAD_FILE_UPLOAD_SUCCESS", "Het leerobject is succesvol ge&iuml;mporteerd als sub-template!");



    define("TEMPLATE_UPLOAD_CANT_UPLOAD_PARENT", "Hoofdtemplates kunnen niet overschreven worden, kies een andere naam voor het sub-template!");



    define("TEMPLATE_UPLOAD_NO_FILE_SELECTED", "Er is geen bestand geselecteerd!");

