<?PHP     



	/**

	 * 

	 * management users english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("USERS_TOGGLE", "Toon");



	define("USERS_ID", "De gebruikers ID is");



	define("USERS_FIRST", "De voornaam van de gebruiker is");



	define("USERS_KNOWN", "De achternaam van de gebruiker is");

	

	define("USERS_USERNAME", "De gebruikersnaam van de gebruiker is");



    define("USERS_MANAGE_AUTH", "Gebruikers met een geldige login");



    define("USERS_MANAGE_ACTIVE", "Actieve gebruikers");

