<?PHP     



	/**

	 * 

	 * management users template english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("USER_GROUPS_MANAGEMENT_SEARCH", "Zoek");



    define("USER_GROUPS_MANAGEMENT_MANAGE", "Manage bestaande groepen");

	

    define("USER_GROUPS_MANAGEMENT_SELECT_GROUP", "Selecteer groep");



	define("USER_GROUPS_MANAGEMENT_ADD", "Voeg nieuwe groep toe");



    define("USER_GROUPS_MANAGEMENT_ADD_GROUP", "Maak nieuwe groep aan");



    define("USER_GROUPS_MANAGEMENT_REMOVE_GROUP", "Verwijder groep");



	define("USER_GROUPS_MANAGEMENT_ALL_USERS", "Alle actieve gebruikers met leerobjecten");



    define("USER_GROUPS_MANAGEMENT_SELECT", "Selecteer gebruiker(s)");



	define("USER_GROUPS_MANAGEMENT_GROUP_MEMBERS", "Alle gebruikers van ");



	define("USER_GROUPS_MANAGEMENT_ADD_MEMBER", "Voeg gebruiker(s) toe aan de geselecteerde groep");



	define("USER_GROUPS_MANAGEMENT_REMOVE_MEMBER", "Verwijder gebruiker van groep");



	define("USER_GROUPS_MANAGEMENT_NO_MEMBERS", "Deze groep heeft op dit moment geen gebruikers");



    define("USER_GROUPS_MANAGEMENT_ONE_MEMBER", "Deze groep heeft op dit moment 1 gebruiker");



    define("USER_GROUPS_MANAGEMENT_MEMBERS_COUNT", "Deze groep heeft op dit moment {n} gebruikers");



    define("USER_GROUPS_MANAGEMENT_GROUP_EXISTS", "Deze groepsnaam wordt al gebruikt");



?>

