<?PHP     



	/**

	 * 

	 * management users template english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("USERS_MANAGEMENT_TEMPLATE_VIEW", "Toon");



	define("USERS_MANAGEMENT_TEMPLATE_SEARCH", "Zoek");



	define("USERS_MANAGEMENT_TEMPLATE_TRANSFER", "Bekijk opties voor eigendomsoverdracht");



	define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_EXPLANATION", "<p>Hier kun je&nbsp;alle (niet-privé) projecten van de geselecteerde gebruiker overdragen aan de nieuwe hieronder geselecteerde eigenaar. De projecten worden in een nieuwe map in de werkruimte van de nieuwe gebruiker geplaatst. De instellingen voor delen veranderen niet. De nieuwe map zal '{user}' heten. Deze map bevat ook submappen als de overgedragen projecten zich in submappen in de werkruimte van de oorspronkelijke eigenaar bevonden.</p><p>Indien hieronder geselecteerd en na een succesvolle overdracht, wordt de oorspronkelijke gebruiker verwijderd uit alle projecten die met hem / haar zijn gedeeld. Als privé projecten&nbsp;ook worden overgedragen, wordt de gebruiker verwijderd uit de lijst met gebruikers waarmee projecten kunnen worden gedeeld en wordt zijn Xerte-account verwijderd. Opmerking: afhankelijk van de gebruikte authenticatiemethode kan de gebruiker mogelijk nog steeds inloggen.</p>");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_PRIVATE", "Draag ook de privé-projecten over.");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_SHARED_FOLDERS", "Neem gedeelde mappen op in de overdracht.");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_DELETEUSER", "Verwijder de toegang van de gebruiker tot leerobjecten die eigendom zijn van andere gebruikers.");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_BUTTON", "Draag geselecteerde projecten over");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_CLOSE_PANEL", "Maak rapport leeg");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_FEEDBACKLINE", "De template met id {template_id} ('{template_name}') is in de folder '{folder}' van gebruiker&nbsp;{newuser} geplaatst en is hernoemd&nbsp;van {oldfolder} naar&nbsp;{newfolder}");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_FEEDBACK_DELETED", "Verwijderd template fgevonden in de prullenbak van {user} (folder {folder})");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_FEEDBACK_REMOVEDFROMRIGHTS", "Gebruiker {user} is verwijderd van {count} projecten.");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_FEEDBACK_REMOVEDFROMLOGINDETAILS", "Gebruiker {user} is verwijderd uit Xerte.");



    define("USERS_MANAGEMENT_TEMPLATE_TRANSFER_FEEDBACK_USERISNOTREMOVED", "Toegang van gebruiker&nbsp;{user} naar andere projecten is niet verwijderd.");



	define("USERS_MANAGEMENT_TEMPLATE_ID", "Het template ID is");



	define("USERS_MANAGEMENT_TEMPLATE_CREATED", "De aanmaak datum is"); 



	define("USERS_MANAGEMENT_TEMPLATE_MODIFIED", "De datum van aanpassing is"); 



	define("USERS_MANAGEMENT_TEMPLATE_ACCESSED", "De laatste toegangsdatum is");



	define("USERS_MANAGEMENT_TEMPLATE_PLAYS", "Het aantal keer bekeken is"); 



	define("USERS_MANAGEMENT_TEMPLATE_ACCESS", "Toegang is ingesteld als"); 	



	define("USERS_MANAGEMENT_TEMPLATE_EDIT", "Verander");



    define("USERS_MANAGEMENT_TEMPLATE_PREVIEW", "Toon");



	define("USERS_MANAGEMENT_TEMPLATE_PROPERTIES", "Eigenschappen");				



	define("USERS_MANAGEMENT_TEMPLATE_GIVE", "Geef het eigenaarschap van dit leerobject aan de geselecteerde gebruiker.");



	define("USERS_MANAGEMENT_TEMPLATE_GIVE_BUTTON", "Verander eigenaar");



	define("USERS_MANAGEMENT_TEMPLATE_NONE", "De gebruiker heeft op dit moment geen templates");



    define("USERS_MANAGEMENT_TEMPLATE_OWNER", "Eigenaar");



    define("USERS_MANAGEMENT_TEMPLATE_ROLE", "Rol");

