<?PHP     



	/**

	 * 

	 * display_library.php english language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("DISPLAY_RECYCLE", "Prullenbak");



	define("DISPLAY_EXAMPLE", "Zie voorbeeld");



	define("DISPLAY_CREATE", "Maak");



    define("DISPLAY_BUTTON_PROJECT_CREATE", "Maak leerobject");



    define("DISPLAY_NAME", "Geef een naam aan dit leerobject");

	

    define("DISPLAY_PROJECT_NAME", "Project naam");



    define("DISPLAY_CHOOSE_AND_NAME", "Kies een template en vul de naam in voor dit leerobject");

	

	define("DISPLAY_TEMPLATE", "Template");



    define("DISPLAY_DEFAULT_TEMPLATE", "Standaard");

	

	define("DISPLAY_ERROR", "Er is een fout opgetreden. Je&nbsp;kunt op dit moment niets wijzigen.");

	

	define("DISPLAY_EDITED", "Dit bestand wordt op dit moment ook gebruikt door&nbsp;");

	

	define("DISPLAY_LOCKFILE_MESSAGE", "<p>Wacht alstublieft tot de huidige auteur&nbsp;klaar is met wijzigen. Als je zeker weet dat dit niet het geval is, kun je het project gaan bewerken door op de onderstaande knop te klikken. Als je doorgaat en er zijn twee auteurs&nbsp;tegelijk aan het bewerken, bestaat het risico dat het project beschadigd raakt. Wacht anders tot de huidige auteur&nbsp;het project gesloten heeft zodat je&nbsp;het weer kunt gebruiken.</p><p>Indien dit per ongeluk toch fout gaat en er zijn&nbsp;pagina's of er is content verdwenen, neem dan zo snel mogelijk contact op met jouw beheerder en blijft direct uit het project. Mogelijk is de inhoud dan nog te herstellen.</p>");



	define("DISPLAY_LOCKFILE_YOU", "jou");



	define("DISPLAY_LOCKFILE_YOU_MESSAGE", "<p>Als je zeker weet dat dit niet het geval is, kun je&nbsp;het project bewerken door op de onderstaande knop te klikken. Als je&nbsp;doorgaat en je&nbsp;bewerkt het project in een andere browser of op een andere pc, bestaat het risico dat je je&nbsp;werk verliest of dat het project beschadigd raakt. Controleer of je&nbsp;het bestand niet in een andere browser of computer&nbsp;open hebt staan.</p><p>Indien dit per ongeluk toch fout gaat en er zijn&nbsp;pagina's of er is content verdwenen, neem dan zo snel mogelijk contact op met jouw beheerder en blijft direct uit het project. Mogelijk is de inhoud dan nog te herstellen.</p>");



	define("DISPLAY_LOCKFILE_DELETE", "Verwijder Lockbestand");



    define("DISPLAY_WORKSPACE","Werkruimte");

