<?PHP



/**

 *

 * sharing status folder template language file

 *

 * @author Patrick Lockley

 * @version 1.0

 * @copyright Pat Lockley

 * @package

 */



define("USER_HAS_TEMPLATES_IN_FOLDER","De gebruiker van wie je&nbsp;de toegang gaat verwijderen, heeft leerobjecten&nbsp;in deze map (of submappen van deze map). Als je&nbsp;de toegang voor deze gebruiker verwijdert, worden de leerobjecten&nbsp;verplaatst naar de hoofdmap van de gebruiker en verliezen alle andere gebruikers de toegang tot de leerobjecten. Wil je doorgaan?");



define("GROUP_HAS_TEMPLATES_IN_FOLDER","Sommige gebruikers van de groep waarvoor je de toegang wilt intrekken, hebben leerobjecten in deze map (of submappen van deze map). Als je&nbsp;de toegang voor deze groep verwijdert, worden deze leerobjecten verplaatst naar de hoofdmap van de maker van het leerobject en verliezen alle andere gebruikers de toegang tot de leerobjecten. Wil je doorgaan?");



define("YOU_HAVE_TEMPLATES_IN_FOLDER","Je hebt leerobjecten in deze map (of submappen van deze map). Als je de&nbsp;toegang verwijdert, worden jouw leerobjecten verplaatst naar jouw hoofdmap en verliezen alle andere gebruikers de toegang tot de leerobjecten. Wil je doorgaan?");



