<?PHP     



	/**

	 * 

	 * folder properties template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("FOLDER_PROPERTIES_PROPERTIES","Eigenschappen map");			



	define("FOLDER_PROPERTIES_CALLED","Deze map heet");

	

	define("FOLDER_PROPERTIES_CHANGE","Pas de naam van de folder aan");



    define("FOLDER_PROPERTIES_BUTTON_SAVE","Hernoem");



    define("FOLDER_PROPERTIES_FAIL","Sorry je hebt geen rechten op deze folder");

