<?PHP     



	/**

	 * 

	 * folder rss template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("FOLDER_RSS_FEEDS","Folder RSS feeds");

	

	define("FOLDER_RSS_PUBLIC","Als deze map openbare inhoud bevat, kun je deze openen via de RSS-feed op");



    define("FOLDER_RSS_FAIL", "Sorry, alleen de eigenaar of co-auteur van de map kan notities voor deze folder&nbsp;maken");

