<?PHP     



	/**

	 * 

	 * sharing status folder template language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */



	define("SHARING_INSTRUCTION","Typ hier de naam van een gebruiker of een groep om de inhoud van deze map te delen. Een gebruiker moet een account op de site hebben (minstens één keer ingelogd) om in deze zoekopdracht te verschijnen. Selecteer ook de&nbsp;rol om de gebruiker of groep aan toe te kennen.");



	define("SHARING_NAMES","De namen verschijnen hier");



	define("SHARING_CURRENT","Dit project wordt op dit moment gedeeld met : ");



    define("SHARING_CREATOR", "Eigenaar");



    define("SHARING_COAUTHOR", "Co-auteur");



    define("SHARING_EDITOR","Ontwikkelaar");



	define("SHARING_READONLY","Alleen lezen");



    define("SHARING_SOURCE","van ");



    define("SHARING_SOURCE_FOLDER","folder");



    define("SHARING_SOURCE_TEMPLATE","leerobject");



    define("SHARING_REMOVE_DESCRIPTION", "Klik op de knop om de gedeelde rechten te verwijderen");



    define("SHARING_REMOVE", "Verwijder");



    define("SHARING_STOP","Klik om het delen van dit project te stoppen");



	define("SHARING_NOT_SHARED","Het pleerobject is niet gedeeld");



    define("SHARING_FAIL","Je hebt geen rechten op dit leerobject");



    define("SHARING_FAIL_SHARED_SUBFOLDER","Je kunt een submap van een gedeelde map niet opnieuw delen");





?>
