<?php



/**

 * Licensed to The Apereo Foundation under one or more contributor license

 * agreements. See the NOTICE file distributed with this work for

 * additional information regarding copyright ownership.



 * The Apereo Foundation licenses this file to you under the Apache License,

 * Version 2.0 (the "License"); you may not use this file except in

 * compliance with the License. You may obtain a copy of the License at:

 *

 * http://www.apache.org/licenses/LICENSE-2.0

 *

 * Unless required by applicable law or agreed to in writing, software

 * distributed under the License is distributed on an "AS IS" BASIS,

 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.



 * See the License for the specific language governing permissions and

 * limitations under the License.

 */





define("IMAGEUPOLOAD_NOT_UPLOADED", "Oeps! Bij het uploaden van het bestand is iets mis gegaan.");

define("IMAGEUPLOAD_INVALID_FORMAT", "Ongeldig soort afbeelding: het kan alleen een png, jpg of gif afbeelding zijn!");

define("IMAGEUPLOAD_RENAMED", "Het bestand is gernoemd van {0} naar {1}");

define("IMAGEUPLOAD_TOO_LARGE", "Het bestand is ({0} bytes) groter dan de toegestane ({1} bytes)");

define("IMAGEUPLOAD_ERROR", "Er was een foutmelding bij het uploaden van de afbeelding:");

define("IMAGEUPLOAD_FORM_SIZE", "Het ge&uuml;ploade bestand is groter dan MAX_FILE_SIZE parameter van het HTML formulier.");

define("IMAGEUPLOAD_PARTIAL_FILE", "Het bestand is slechts gedeeltelijk ge&uuml;pload.");

define("IMAGEUPLOAD_NO_FILE", "Er is geen bestand ge&uuml;pload.");

define("IMAGEUPLOAD_NO_TMP_DIR", "De tijdelijke folder mist.");

define("IMAGEUPLOAD_CANT_WRITE", "Het opslaan van het bestand is mislukt.");

define("IMAGEUPLOAD_EXTENSION", "Het opslaan van het bestand is verhinderd door de extensie.");



