<?PHP     



	/**

	 * 

	 * template close language file

	 *

	 * @author Patrick Lockley

	 * @version 1.0

	 * @copyright Pat Lockley

	 * @package

	 */

	 



	define("TEMPLATE_CLOSE_FILE","Bestand beschikbaar");



	define("TEMPLATE_CLOSE_EMAIL_GREETINGS","Hallo,"); 



	define("TEMPLATE_CLOSE_EMAIL_INTRODUCTION","U heeft gevraagd om geïnformeerd te worden wanneer het bestand");



	define("TEMPLATE_CLOSE_EMAIL_MESSAGE","Beschikbaar is voor bewerking. Het bestand is beschikbaar gemaakt op");

 

	define("TEMPLATE_CLOSE_EMAIL_MESSAGE_MORE","Houd er rekening meer dat er meerdere verzoeken gedaan zijn en dat je niet de enige persoon bent die deze berichten heeft ontvangen. Het bestand kan beveiligd zijn door iemand anders.");



	define("TEMPLATE_CLOSE_EMAIL_LOG_IN","Log in op de website op");

 

	define("TEMPLATE_CLOSE_EMAIL_CLOSING_SUBJECT","Dank u,");

 

	define("TEMPLATE_CLOSE_EMAIL_SIGNATURE","het team van Xerte Online Toolkits ");



	define("TEMPLATE_CLOSE_QUESTION","Moeten de veranderingen gepubliceerd worden?");





